FORMAT: 1A
HOST: http://sismotecapi.herokuapp.com

# Sismo Tec API

Sismo TEC REST API that supports Sismo Tec apps.

## Base URL
All production requests are made to: <br />
http://sismotecapi.herokuapp.com

## Mock URL
All mock requests are made to: <br />
http://private-58094-sismotecapi.apiary-mock.com/

## REST
Sismo Tec API is a RESTful API:
- It makes use of native concepts and techniques of HTTP
- It follows the constraints of REST
- It is defined in terms of endpoints and parameters

## JSON
The Sismo Tec API uses exclusively JSON, so you should always set the
<strong>Content-type</strong> header to <strong>application/json</strong>. 


## Sismo Tec API Root [/]
This resource is our traditional "Hello World!".

### Get the entry point [GET]

+ Response 200 (application/json; charset=utf-8)

    + Attributes
    
        + message: 'Hello World! This is SismoTec API!' (string)